name: graps_gui
channels:
  - conda-forge
  - defaults
dependencies:
  - backcall=0.1.0
  - blas=1.0
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - colorama=0.4.3
  - cycler=0.10.0
  - decorator=4.4.2
  - freetype=2.10.2
  - future=0.18.2
  - icu=64.2
  - intel-openmp=2019.4
  - ipython=7.14.0
  - ipython_genutils=0.2.0
  - jedi=0.17.0
  - jpeg=9c
  - kiwisolver=1.2.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - liblapack=3.8.0
  - libpng=1.6.37
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - networkx=2.4
  - numpy=1.18.5
  - openssl=1.1.1g
  - pandas=1.0.5
  - parso=0.7.0
  - patsy=0.5.1
  - pickleshare=0.7.5
  - pip=20.1.1
  - prompt-toolkit=3.0.5
  - pygments=2.6.1
  - pyparsing=2.4.7
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - qt=5.12.5
  - scipy=1.3.1
  - seaborn=0.10.1
  - seaborn-base=0.10.1
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.30.1
  - statsmodels=0.11.1
  - tornado=6.0.4
  - traitlets=4.3.3
  - wcwidth=0.1.9
  - wheel=0.34.2
  - zlib=1.2.11
