name: graps_gui
channels:
  - conda-forge
  - defaults
dependencies:
  - backcall=0.1.0
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - colorama=0.4.3
  - decorator=4.4.2
  - future=0.18.2
  - icu=64.2
  - ipython=7.14.0
  - ipython_genutils=0.2.0
  - jedi=0.17.0
  - jpeg=9c
  - libclang=9.0.1
  - libpng=1.6.37
  - openssl=1.1.1g
  - parso=0.7.0
  - pickleshare=0.7.5
  - pip=20.1
  - prompt-toolkit=3.0.5
  - pygments=2.6.1
  - pyqt=5.12.3
  - python=3.7.6
  - python_abi=3.7
  - qt=5.12.5
  - setuptools=46.1.3
  - six=1.14.0
  - sqlite=3.30.1
  - traitlets=4.3.3
  - wcwidth=0.1.9
  - wheel=0.34.2
  - zlib=1.2.11
  - pip:
      - pyqt5-sip
      - pyqtchart
      - pyqtwebengine
