# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\plot_display_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_plot_display_dialog(object):
    def setupUi(self, plot_display_dialog):
        plot_display_dialog.setObjectName("plot_display_dialog")
        plot_display_dialog.resize(683, 441)
        self.horizontalLayout = QtWidgets.QHBoxLayout(plot_display_dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.display_window = QtWidgets.QWidget(plot_display_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display_window.sizePolicy().hasHeightForWidth())
        self.display_window.setSizePolicy(sizePolicy)
        self.display_window.setObjectName("display_window")
        self.display_vert_layout = QtWidgets.QVBoxLayout(self.display_window)
        self.display_vert_layout.setObjectName("display_vert_layout")
        self.horizontalLayout.addWidget(self.display_window)
        self.plot_list = QtWidgets.QListWidget(plot_display_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plot_list.sizePolicy().hasHeightForWidth())
        self.plot_list.setSizePolicy(sizePolicy)
        self.plot_list.setMaximumSize(QtCore.QSize(200, 16777215))
        self.plot_list.setObjectName("plot_list")
        self.horizontalLayout.addWidget(self.plot_list)

        self.retranslateUi(plot_display_dialog)
        QtCore.QMetaObject.connectSlotsByName(plot_display_dialog)

    def retranslateUi(self, plot_display_dialog):
        _translate = QtCore.QCoreApplication.translate
        plot_display_dialog.setWindowTitle(_translate("plot_display_dialog", "Dialog"))
