# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\reservoir_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_reservoirDialog(object):
    def setupUi(self, reservoirDialog):
        reservoirDialog.setObjectName("reservoirDialog")
        reservoirDialog.resize(727, 518)
        self.gridLayout = QtWidgets.QGridLayout(reservoirDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.ident_reservoir = QtWidgets.QLineEdit(reservoirDialog)
        self.ident_reservoir.setEnabled(False)
        self.ident_reservoir.setObjectName("ident_reservoir")
        self.gridLayout.addWidget(self.ident_reservoir, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(reservoirDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 1, 1, 1)
        self.res_tab_widget = QtWidgets.QTabWidget(reservoirDialog)
        self.res_tab_widget.setObjectName("res_tab_widget")
        self.reservoir_desc_tab = QtWidgets.QWidget()
        self.reservoir_desc_tab.setObjectName("reservoir_desc_tab")
        self.description_box = QtWidgets.QGroupBox(self.reservoir_desc_tab)
        self.description_box.setGeometry(QtCore.QRect(10, 10, 371, 294))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.description_box.setFont(font)
        self.description_box.setObjectName("description_box")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.description_box)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ID_label = QtWidgets.QLabel(self.description_box)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ID_label.setFont(font)
        self.ID_label.setObjectName("ID_label")
        self.gridLayout_2.addWidget(self.ID_label, 0, 0, 1, 1)
        self.name_label = QtWidgets.QLabel(self.description_box)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.gridLayout_2.addWidget(self.name_label, 1, 0, 1, 1)
        self.latitude_label = QtWidgets.QLabel(self.description_box)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.latitude_label.setFont(font)
        self.latitude_label.setObjectName("latitude_label")
        self.gridLayout_2.addWidget(self.latitude_label, 2, 0, 1, 1)
        self.latitude_edit = QtWidgets.QLineEdit(self.description_box)
        self.latitude_edit.setObjectName("latitude_edit")
        self.gridLayout_2.addWidget(self.latitude_edit, 2, 1, 1, 1)
        self.longitude_label = QtWidgets.QLabel(self.description_box)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.longitude_label.setFont(font)
        self.longitude_label.setObjectName("longitude_label")
        self.gridLayout_2.addWidget(self.longitude_label, 3, 0, 1, 1)
        self.longitude_edit = QtWidgets.QLineEdit(self.description_box)
        self.longitude_edit.setObjectName("longitude_edit")
        self.gridLayout_2.addWidget(self.longitude_edit, 3, 1, 1, 1)
        self.min_elev_label = QtWidgets.QLabel(self.description_box)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.min_elev_label.setFont(font)
        self.min_elev_label.setObjectName("min_elev_label")
        self.gridLayout_2.addWidget(self.min_elev_label, 4, 0, 1, 1)
        self.min_elev_edit = QtWidgets.QLineEdit(self.description_box)
        self.min_elev_edit.setObjectName("min_elev_edit")
        self.gridLayout_2.addWidget(self.min_elev_edit, 4, 1, 1, 1)
        self.min_elev_unit = QtWidgets.QLabel(self.description_box)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.min_elev_unit.setFont(font)
        self.min_elev_unit.setObjectName("min_elev_unit")
        self.gridLayout_2.addWidget(self.min_elev_unit, 4, 2, 1, 1)
        self.max_elev_label = QtWidgets.QLabel(self.description_box)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.max_elev_label.setFont(font)
        self.max_elev_label.setObjectName("max_elev_label")
        self.gridLayout_2.addWidget(self.max_elev_label, 5, 0, 1, 1)
        self.max_elev_edit = QtWidgets.QLineEdit(self.description_box)
        self.max_elev_edit.setObjectName("max_elev_edit")
        self.gridLayout_2.addWidget(self.max_elev_edit, 5, 1, 1, 1)
        self.max_elev_unit = QtWidgets.QLabel(self.description_box)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.max_elev_unit.setFont(font)
        self.max_elev_unit.setObjectName("max_elev_unit")
        self.gridLayout_2.addWidget(self.max_elev_unit, 5, 2, 1, 1)
        self.min_stor_label = QtWidgets.QLabel(self.description_box)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.min_stor_label.setFont(font)
        self.min_stor_label.setObjectName("min_stor_label")
        self.gridLayout_2.addWidget(self.min_stor_label, 6, 0, 1, 1)
        self.min_stor_edit = QtWidgets.QLineEdit(self.description_box)
        self.min_stor_edit.setObjectName("min_stor_edit")
        self.gridLayout_2.addWidget(self.min_stor_edit, 6, 1, 1, 1)
        self.min_stor_unit = QtWidgets.QLabel(self.description_box)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.min_stor_unit.setFont(font)
        self.min_stor_unit.setObjectName("min_stor_unit")
        self.gridLayout_2.addWidget(self.min_stor_unit, 6, 2, 1, 1)
        self.max_stor_label = QtWidgets.QLabel(self.description_box)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.max_stor_label.setFont(font)
        self.max_stor_label.setObjectName("max_stor_label")
        self.gridLayout_2.addWidget(self.max_stor_label, 7, 0, 1, 1)
        self.max_stor_label_2 = QtWidgets.QLineEdit(self.description_box)
        self.max_stor_label_2.setObjectName("max_stor_label_2")
        self.gridLayout_2.addWidget(self.max_stor_label_2, 7, 1, 1, 1)
        self.max_stor_unit = QtWidgets.QLabel(self.description_box)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.max_stor_unit.setFont(font)
        self.max_stor_unit.setObjectName("max_stor_unit")
        self.gridLayout_2.addWidget(self.max_stor_unit, 7, 2, 1, 1)
        self.current_stor_label = QtWidgets.QLabel(self.description_box)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.current_stor_label.setFont(font)
        self.current_stor_label.setObjectName("current_stor_label")
        self.gridLayout_2.addWidget(self.current_stor_label, 8, 0, 1, 1)
        self.current_stor_edit = QtWidgets.QLineEdit(self.description_box)
        self.current_stor_edit.setObjectName("current_stor_edit")
        self.gridLayout_2.addWidget(self.current_stor_edit, 8, 1, 1, 1)
        self.current_stor_unit = QtWidgets.QLabel(self.description_box)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.current_stor_unit.setFont(font)
        self.current_stor_unit.setObjectName("current_stor_unit")
        self.gridLayout_2.addWidget(self.current_stor_unit, 8, 2, 1, 1)
        self.name_edit = QtWidgets.QLineEdit(self.description_box)
        self.name_edit.setObjectName("name_edit")
        self.gridLayout_2.addWidget(self.name_edit, 1, 1, 1, 2)
        self.reservoir_id_display = QtWidgets.QLabel(self.description_box)
        self.reservoir_id_display.setObjectName("reservoir_id_display")
        self.gridLayout_2.addWidget(self.reservoir_id_display, 0, 1, 1, 1)
        self.res_tab_widget.addTab(self.reservoir_desc_tab, "")
        self.evaporation_tab = QtWidgets.QWidget()
        self.evaporation_tab.setObjectName("evaporation_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.evaporation_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 2, 0, 1, 1)
        self.evap_box = QtWidgets.QGroupBox(self.evaporation_tab)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.evap_box.setFont(font)
        self.evap_box.setObjectName("evap_box")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.evap_box)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.evap_table = QtWidgets.QTableWidget(self.evap_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evap_table.sizePolicy().hasHeightForWidth())
        self.evap_table.setSizePolicy(sizePolicy)
        self.evap_table.setRowCount(1)
        self.evap_table.setColumnCount(12)
        self.evap_table.setObjectName("evap_table")
        item = QtWidgets.QTableWidgetItem()
        self.evap_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.evap_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.evap_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.evap_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.evap_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.evap_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.evap_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.evap_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.evap_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.evap_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.evap_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.evap_table.setHorizontalHeaderItem(11, item)
        self.gridLayout_4.addWidget(self.evap_table, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.evap_box, 1, 0, 1, 2)
        self.evap_file_box = QtWidgets.QGroupBox(self.evaporation_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.evap_file_box.sizePolicy().hasHeightForWidth())
        self.evap_file_box.setSizePolicy(sizePolicy)
        self.evap_file_box.setMinimumSize(QtCore.QSize(500, 0))
        self.evap_file_box.setObjectName("evap_file_box")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.evap_file_box)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.select_evap_file = QtWidgets.QPushButton(self.evap_file_box)
        self.select_evap_file.setObjectName("select_evap_file")
        self.gridLayout_15.addWidget(self.select_evap_file, 0, 0, 1, 1)
        self.evap_file_edit = QtWidgets.QLineEdit(self.evap_file_box)
        self.evap_file_edit.setEnabled(False)
        self.evap_file_edit.setObjectName("evap_file_edit")
        self.gridLayout_15.addWidget(self.evap_file_edit, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.evap_file_box, 0, 1, 1, 1)
        self.input_method_box_2 = QtWidgets.QGroupBox(self.evaporation_tab)
        self.input_method_box_2.setObjectName("input_method_box_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.input_method_box_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.table_radio_3 = QtWidgets.QRadioButton(self.input_method_box_2)
        self.table_radio_3.setObjectName("table_radio_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.table_radio_3)
        self.input_radio_2 = QtWidgets.QRadioButton(self.input_method_box_2)
        self.input_radio_2.setObjectName("input_radio_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.input_radio_2)
        self.gridLayout_3.addWidget(self.input_method_box_2, 0, 0, 1, 1)
        self.res_tab_widget.addTab(self.evaporation_tab, "")
        self.storage_elev_tab = QtWidgets.QWidget()
        self.storage_elev_tab.setObjectName("storage_elev_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.storage_elev_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 3, 0, 1, 1)
        self.level_vol_area_box = QtWidgets.QGroupBox(self.storage_elev_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.level_vol_area_box.sizePolicy().hasHeightForWidth())
        self.level_vol_area_box.setSizePolicy(sizePolicy)
        self.level_vol_area_box.setObjectName("level_vol_area_box")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.level_vol_area_box)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.select_file = QtWidgets.QPushButton(self.level_vol_area_box)
        self.select_file.setObjectName("select_file")
        self.gridLayout_7.addWidget(self.select_file, 2, 0, 1, 1)
        self.select_file_field = QtWidgets.QLineEdit(self.level_vol_area_box)
        self.select_file_field.setEnabled(False)
        self.select_file_field.setObjectName("select_file_field")
        self.gridLayout_7.addWidget(self.select_file_field, 2, 1, 1, 1)
        self.lev_vol_area_label = QtWidgets.QLabel(self.level_vol_area_box)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lev_vol_area_label.setFont(font)
        self.lev_vol_area_label.setObjectName("lev_vol_area_label")
        self.gridLayout_7.addWidget(self.lev_vol_area_label, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.level_vol_area_box, 2, 0, 1, 2)
        self.storage_elev_det_box = QtWidgets.QGroupBox(self.storage_elev_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.storage_elev_det_box.sizePolicy().hasHeightForWidth())
        self.storage_elev_det_box.setSizePolicy(sizePolicy)
        self.storage_elev_det_box.setObjectName("storage_elev_det_box")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.storage_elev_det_box)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.elev_area_coeff_label = QtWidgets.QLabel(self.storage_elev_det_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elev_area_coeff_label.sizePolicy().hasHeightForWidth())
        self.elev_area_coeff_label.setSizePolicy(sizePolicy)
        self.elev_area_coeff_label.setObjectName("elev_area_coeff_label")
        self.gridLayout_6.addWidget(self.elev_area_coeff_label, 1, 0, 1, 1)
        self.elev_alpha_edit = QtWidgets.QLineEdit(self.storage_elev_det_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elev_alpha_edit.sizePolicy().hasHeightForWidth())
        self.elev_alpha_edit.setSizePolicy(sizePolicy)
        self.elev_alpha_edit.setObjectName("elev_alpha_edit")
        self.gridLayout_6.addWidget(self.elev_alpha_edit, 1, 1, 1, 1)
        self.elev_beta_edit = QtWidgets.QLineEdit(self.storage_elev_det_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elev_beta_edit.sizePolicy().hasHeightForWidth())
        self.elev_beta_edit.setSizePolicy(sizePolicy)
        self.elev_beta_edit.setObjectName("elev_beta_edit")
        self.gridLayout_6.addWidget(self.elev_beta_edit, 1, 2, 1, 1)
        self.elev__gamma_edit = QtWidgets.QLineEdit(self.storage_elev_det_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.elev__gamma_edit.sizePolicy().hasHeightForWidth())
        self.elev__gamma_edit.setSizePolicy(sizePolicy)
        self.elev__gamma_edit.setObjectName("elev__gamma_edit")
        self.gridLayout_6.addWidget(self.elev__gamma_edit, 1, 3, 1, 1)
        self.vol_area_coeff = QtWidgets.QLabel(self.storage_elev_det_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vol_area_coeff.sizePolicy().hasHeightForWidth())
        self.vol_area_coeff.setSizePolicy(sizePolicy)
        self.vol_area_coeff.setObjectName("vol_area_coeff")
        self.gridLayout_6.addWidget(self.vol_area_coeff, 2, 0, 1, 1)
        self.vol_alpha_edit = QtWidgets.QLineEdit(self.storage_elev_det_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vol_alpha_edit.sizePolicy().hasHeightForWidth())
        self.vol_alpha_edit.setSizePolicy(sizePolicy)
        self.vol_alpha_edit.setObjectName("vol_alpha_edit")
        self.gridLayout_6.addWidget(self.vol_alpha_edit, 2, 1, 1, 1)
        self.vol_beta_edit = QtWidgets.QLineEdit(self.storage_elev_det_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vol_beta_edit.sizePolicy().hasHeightForWidth())
        self.vol_beta_edit.setSizePolicy(sizePolicy)
        self.vol_beta_edit.setObjectName("vol_beta_edit")
        self.gridLayout_6.addWidget(self.vol_beta_edit, 2, 2, 1, 1)
        self.vol__gamma_edit = QtWidgets.QLineEdit(self.storage_elev_det_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vol__gamma_edit.sizePolicy().hasHeightForWidth())
        self.vol__gamma_edit.setSizePolicy(sizePolicy)
        self.vol__gamma_edit.setObjectName("vol__gamma_edit")
        self.gridLayout_6.addWidget(self.vol__gamma_edit, 2, 3, 1, 1)
        self.alpha_label = QtWidgets.QLabel(self.storage_elev_det_box)
        self.alpha_label.setMidLineWidth(7)
        self.alpha_label.setAlignment(QtCore.Qt.AlignCenter)
        self.alpha_label.setObjectName("alpha_label")
        self.gridLayout_6.addWidget(self.alpha_label, 0, 1, 1, 1)
        self.beta_label = QtWidgets.QLabel(self.storage_elev_det_box)
        self.beta_label.setMidLineWidth(7)
        self.beta_label.setAlignment(QtCore.Qt.AlignCenter)
        self.beta_label.setObjectName("beta_label")
        self.gridLayout_6.addWidget(self.beta_label, 0, 2, 1, 1)
        self.gamma_label = QtWidgets.QLabel(self.storage_elev_det_box)
        self.gamma_label.setMidLineWidth(7)
        self.gamma_label.setAlignment(QtCore.Qt.AlignCenter)
        self.gamma_label.setObjectName("gamma_label")
        self.gridLayout_6.addWidget(self.gamma_label, 0, 3, 1, 1)
        self.gridLayout_5.addWidget(self.storage_elev_det_box, 1, 0, 1, 2)
        self.select_type_box = QtWidgets.QGroupBox(self.storage_elev_tab)
        self.select_type_box.setObjectName("select_type_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.select_type_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.coeff_radio = QtWidgets.QRadioButton(self.select_type_box)
        self.coeff_radio.setObjectName("coeff_radio")
        self.verticalLayout.addWidget(self.coeff_radio)
        self.table_radio = QtWidgets.QRadioButton(self.select_type_box)
        self.table_radio.setObjectName("table_radio")
        self.verticalLayout.addWidget(self.table_radio)
        self.gridLayout_5.addWidget(self.select_type_box, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem3, 2, 2, 1, 1)
        self.res_tab_widget.addTab(self.storage_elev_tab, "")
        self.oper_info_tab = QtWidgets.QWidget()
        self.oper_info_tab.setObjectName("oper_info_tab")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.oper_info_tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.oper_info_box = QtWidgets.QGroupBox(self.oper_info_tab)
        self.oper_info_box.setObjectName("oper_info_box")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.oper_info_box)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.targ_stor_label = QtWidgets.QLabel(self.oper_info_box)
        self.targ_stor_label.setObjectName("targ_stor_label")
        self.gridLayout_11.addWidget(self.targ_stor_label, 0, 0, 1, 1)
        self.tar_stor_edit = QtWidgets.QLineEdit(self.oper_info_box)
        self.tar_stor_edit.setObjectName("tar_stor_edit")
        self.gridLayout_11.addWidget(self.tar_stor_edit, 0, 1, 1, 1)
        self.tar_stor_unit = QtWidgets.QLabel(self.oper_info_box)
        self.tar_stor_unit.setObjectName("tar_stor_unit")
        self.gridLayout_11.addWidget(self.tar_stor_unit, 0, 2, 1, 1)
        self.stor_prob_label = QtWidgets.QLabel(self.oper_info_box)
        self.stor_prob_label.setObjectName("stor_prob_label")
        self.gridLayout_11.addWidget(self.stor_prob_label, 1, 0, 1, 1)
        self.stor_prob_edit = QtWidgets.QLineEdit(self.oper_info_box)
        self.stor_prob_edit.setObjectName("stor_prob_edit")
        self.gridLayout_11.addWidget(self.stor_prob_edit, 1, 1, 1, 1)
        self.gridLayout_8.addWidget(self.oper_info_box, 0, 0, 1, 1)
        self.rule_curve_box = QtWidgets.QGroupBox(self.oper_info_tab)
        self.rule_curve_box.setObjectName("rule_curve_box")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.rule_curve_box)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.curve_file_select = QtWidgets.QPushButton(self.rule_curve_box)
        self.curve_file_select.setObjectName("curve_file_select")
        self.gridLayout_9.addWidget(self.curve_file_select, 1, 0, 1, 1)
        self.curve_file_edit = QtWidgets.QLineEdit(self.rule_curve_box)
        self.curve_file_edit.setEnabled(False)
        self.curve_file_edit.setObjectName("curve_file_edit")
        self.gridLayout_9.addWidget(self.curve_file_edit, 1, 1, 1, 1)
        self.rule_curve_table = QtWidgets.QTableWidget(self.rule_curve_box)
        self.rule_curve_table.setObjectName("rule_curve_table")
        self.rule_curve_table.setColumnCount(12)
        self.rule_curve_table.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.rule_curve_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_curve_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_curve_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_curve_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_curve_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_curve_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_curve_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_curve_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_curve_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_curve_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_curve_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_curve_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_curve_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_curve_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_curve_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.rule_curve_table.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(1, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(1, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(1, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(1, 10, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(1, 11, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(3, 7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(3, 8, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(3, 9, item)
        item = QtWidgets.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(3, 10, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.rule_curve_table.setItem(3, 11, item)
        self.gridLayout_9.addWidget(self.rule_curve_table, 0, 0, 1, 2)
        self.gridLayout_8.addWidget(self.rule_curve_box, 1, 0, 1, 2)
        self.target_rest_box = QtWidgets.QGroupBox(self.oper_info_tab)
        self.target_rest_box.setObjectName("target_rest_box")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.target_rest_box)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.target_rest_table = QtWidgets.QTableWidget(self.target_rest_box)
        self.target_rest_table.setObjectName("target_rest_table")
        self.target_rest_table.setColumnCount(3)
        self.target_rest_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.target_rest_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.target_rest_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.target_rest_table.setHorizontalHeaderItem(2, item)
        self.gridLayout_10.addWidget(self.target_rest_table, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.target_rest_box, 2, 0, 1, 2)
        self.input_method_box = QtWidgets.QGroupBox(self.oper_info_tab)
        self.input_method_box.setObjectName("input_method_box")
        self.formLayout = QtWidgets.QFormLayout(self.input_method_box)
        self.formLayout.setObjectName("formLayout")
        self.table_radio_2 = QtWidgets.QRadioButton(self.input_method_box)
        self.table_radio_2.setObjectName("table_radio_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.table_radio_2)
        self.input_radio = QtWidgets.QRadioButton(self.input_method_box)
        self.input_radio.setObjectName("input_radio")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.input_radio)
        self.gridLayout_8.addWidget(self.input_method_box, 0, 1, 1, 1)
        self.res_tab_widget.addTab(self.oper_info_tab, "")
        self.spill_out_tab = QtWidgets.QWidget()
        self.spill_out_tab.setObjectName("spill_out_tab")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.spill_out_tab)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.spillway_box = QtWidgets.QGroupBox(self.spill_out_tab)
        self.spillway_box.setObjectName("spillway_box")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.spillway_box)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.spillway_table = QtWidgets.QTableWidget(self.spillway_box)
        self.spillway_table.setMinimumSize(QtCore.QSize(653, 0))
        self.spillway_table.setTextElideMode(QtCore.Qt.ElideLeft)
        self.spillway_table.setGridStyle(QtCore.Qt.NoPen)
        self.spillway_table.setRowCount(1)
        self.spillway_table.setObjectName("spillway_table")
        self.spillway_table.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.spillway_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.spillway_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.spillway_table.setHorizontalHeaderItem(2, item)
        self.spillway_table.horizontalHeader().setCascadingSectionResizes(True)
        self.spillway_table.horizontalHeader().setHighlightSections(True)
        self.spillway_table.horizontalHeader().setMinimumSectionSize(100)
        self.spillway_table.horizontalHeader().setSortIndicatorShown(False)
        self.spillway_table.horizontalHeader().setStretchLastSection(False)
        self.spillway_table.verticalHeader().setStretchLastSection(False)
        self.gridLayout_14.addWidget(self.spillway_table, 1, 0, 1, 4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem4, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem5, 0, 3, 1, 1)
        self.num_spill_edit = QtWidgets.QLineEdit(self.spillway_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_spill_edit.sizePolicy().hasHeightForWidth())
        self.num_spill_edit.setSizePolicy(sizePolicy)
        self.num_spill_edit.setObjectName("num_spill_edit")
        self.gridLayout_14.addWidget(self.num_spill_edit, 0, 2, 1, 1)
        self.num_spill_label = QtWidgets.QLabel(self.spillway_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_spill_label.sizePolicy().hasHeightForWidth())
        self.num_spill_label.setSizePolicy(sizePolicy)
        self.num_spill_label.setObjectName("num_spill_label")
        self.gridLayout_14.addWidget(self.num_spill_label, 0, 0, 1, 1)
        self.gridLayout_12.addWidget(self.spillway_box, 0, 0, 1, 1)
        self.outlet_box = QtWidgets.QGroupBox(self.spill_out_tab)
        self.outlet_box.setObjectName("outlet_box")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.outlet_box)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.outlet_table = QtWidgets.QTableWidget(self.outlet_box)
        self.outlet_table.setRowCount(1)
        self.outlet_table.setObjectName("outlet_table")
        self.outlet_table.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.outlet_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.outlet_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.outlet_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.outlet_table.setHorizontalHeaderItem(3, item)
        self.gridLayout_13.addWidget(self.outlet_table, 1, 0, 1, 4)
        self.num_outlet_label = QtWidgets.QLabel(self.outlet_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_outlet_label.sizePolicy().hasHeightForWidth())
        self.num_outlet_label.setSizePolicy(sizePolicy)
        self.num_outlet_label.setObjectName("num_outlet_label")
        self.gridLayout_13.addWidget(self.num_outlet_label, 0, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem6, 0, 3, 1, 1)
        self.num_outlet_edit = QtWidgets.QLineEdit(self.outlet_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.num_outlet_edit.sizePolicy().hasHeightForWidth())
        self.num_outlet_edit.setSizePolicy(sizePolicy)
        self.num_outlet_edit.setObjectName("num_outlet_edit")
        self.gridLayout_13.addWidget(self.num_outlet_edit, 0, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem7, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.outlet_box, 1, 0, 1, 1)
        self.res_tab_widget.addTab(self.spill_out_tab, "")
        self.gridLayout.addWidget(self.res_tab_widget, 0, 0, 1, 2)
        self.name_label.setBuddy(self.name_edit)
        self.latitude_label.setBuddy(self.latitude_edit)
        self.longitude_label.setBuddy(self.longitude_edit)
        self.min_elev_label.setBuddy(self.min_elev_edit)
        self.max_elev_label.setBuddy(self.max_elev_edit)
        self.min_stor_label.setBuddy(self.min_stor_edit)
        self.max_stor_label.setBuddy(self.max_stor_label_2)
        self.current_stor_label.setBuddy(self.current_stor_edit)
        self.elev_area_coeff_label.setBuddy(self.elev_alpha_edit)
        self.vol_area_coeff.setBuddy(self.vol_alpha_edit)
        self.targ_stor_label.setBuddy(self.tar_stor_edit)
        self.stor_prob_label.setBuddy(self.stor_prob_edit)
        self.num_spill_label.setBuddy(self.num_spill_edit)
        self.num_outlet_label.setBuddy(self.num_outlet_edit)

        self.retranslateUi(reservoirDialog)
        self.res_tab_widget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(reservoirDialog.accept)
        self.buttonBox.rejected.connect(reservoirDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(reservoirDialog)
        reservoirDialog.setTabOrder(self.name_edit, self.latitude_edit)
        reservoirDialog.setTabOrder(self.latitude_edit, self.longitude_edit)
        reservoirDialog.setTabOrder(self.longitude_edit, self.min_elev_edit)
        reservoirDialog.setTabOrder(self.min_elev_edit, self.max_elev_edit)
        reservoirDialog.setTabOrder(self.max_elev_edit, self.min_stor_edit)
        reservoirDialog.setTabOrder(self.min_stor_edit, self.max_stor_label_2)
        reservoirDialog.setTabOrder(self.max_stor_label_2, self.current_stor_edit)
        reservoirDialog.setTabOrder(self.current_stor_edit, self.coeff_radio)
        reservoirDialog.setTabOrder(self.coeff_radio, self.table_radio)
        reservoirDialog.setTabOrder(self.table_radio, self.elev_alpha_edit)
        reservoirDialog.setTabOrder(self.elev_alpha_edit, self.elev_beta_edit)
        reservoirDialog.setTabOrder(self.elev_beta_edit, self.elev__gamma_edit)
        reservoirDialog.setTabOrder(self.elev__gamma_edit, self.vol_alpha_edit)
        reservoirDialog.setTabOrder(self.vol_alpha_edit, self.vol_beta_edit)
        reservoirDialog.setTabOrder(self.vol_beta_edit, self.vol__gamma_edit)
        reservoirDialog.setTabOrder(self.vol__gamma_edit, self.select_file)
        reservoirDialog.setTabOrder(self.select_file, self.select_file_field)
        reservoirDialog.setTabOrder(self.select_file_field, self.tar_stor_edit)
        reservoirDialog.setTabOrder(self.tar_stor_edit, self.stor_prob_edit)
        reservoirDialog.setTabOrder(self.stor_prob_edit, self.rule_curve_table)
        reservoirDialog.setTabOrder(self.rule_curve_table, self.target_rest_table)
        reservoirDialog.setTabOrder(self.target_rest_table, self.num_spill_edit)
        reservoirDialog.setTabOrder(self.num_spill_edit, self.spillway_table)
        reservoirDialog.setTabOrder(self.spillway_table, self.num_outlet_edit)
        reservoirDialog.setTabOrder(self.num_outlet_edit, self.outlet_table)
        reservoirDialog.setTabOrder(self.outlet_table, self.ident_reservoir)
        reservoirDialog.setTabOrder(self.ident_reservoir, self.buttonBox)
        reservoirDialog.setTabOrder(self.buttonBox, self.res_tab_widget)

    def retranslateUi(self, reservoirDialog):
        _translate = QtCore.QCoreApplication.translate
        reservoirDialog.setWindowTitle(_translate("reservoirDialog", "Reservoir"))
        self.description_box.setTitle(_translate("reservoirDialog", "Description"))
        self.ID_label.setText(_translate("reservoirDialog", "Reservoir ID"))
        self.name_label.setText(_translate("reservoirDialog", "Name"))
        self.latitude_label.setText(_translate("reservoirDialog", "Latitude"))
        self.longitude_label.setText(_translate("reservoirDialog", "Longitude"))
        self.min_elev_label.setText(_translate("reservoirDialog", "Elevation Minimum (from datum) "))
        self.min_elev_unit.setText(_translate("reservoirDialog", "Meters"))
        self.max_elev_label.setText(_translate("reservoirDialog", "Elevation Maximum (from datum)"))
        self.max_elev_unit.setText(_translate("reservoirDialog", "Meters"))
        self.min_stor_label.setText(_translate("reservoirDialog", "Storage Minimum"))
        self.min_stor_unit.setText(_translate("reservoirDialog", "Mm"))
        self.max_stor_label.setText(_translate("reservoirDialog", "Storage Maximum"))
        self.max_stor_unit.setText(_translate("reservoirDialog", "Mm"))
        self.current_stor_label.setText(_translate("reservoirDialog", "Current Storage"))
        self.current_stor_unit.setText(_translate("reservoirDialog", "Mm"))
        self.reservoir_id_display.setText(_translate("reservoirDialog", "1"))
        self.res_tab_widget.setTabText(self.res_tab_widget.indexOf(self.reservoir_desc_tab), _translate("reservoirDialog", "Reservoir Description"))
        self.evap_box.setTitle(_translate("reservoirDialog", "Evaportation (Meters)"))
        item = self.evap_table.horizontalHeaderItem(0)
        item.setText(_translate("reservoirDialog", "1"))
        item = self.evap_table.horizontalHeaderItem(1)
        item.setText(_translate("reservoirDialog", "2"))
        item = self.evap_table.horizontalHeaderItem(2)
        item.setText(_translate("reservoirDialog", "3"))
        item = self.evap_table.horizontalHeaderItem(3)
        item.setText(_translate("reservoirDialog", "4"))
        item = self.evap_table.horizontalHeaderItem(4)
        item.setText(_translate("reservoirDialog", "5"))
        item = self.evap_table.horizontalHeaderItem(5)
        item.setText(_translate("reservoirDialog", "6"))
        item = self.evap_table.horizontalHeaderItem(6)
        item.setText(_translate("reservoirDialog", "7"))
        item = self.evap_table.horizontalHeaderItem(7)
        item.setText(_translate("reservoirDialog", "8"))
        item = self.evap_table.horizontalHeaderItem(8)
        item.setText(_translate("reservoirDialog", "9"))
        item = self.evap_table.horizontalHeaderItem(9)
        item.setText(_translate("reservoirDialog", "10"))
        item = self.evap_table.horizontalHeaderItem(10)
        item.setText(_translate("reservoirDialog", "11"))
        item = self.evap_table.horizontalHeaderItem(11)
        item.setText(_translate("reservoirDialog", "12"))
        self.evap_file_box.setTitle(_translate("reservoirDialog", "Evaporation File"))
        self.select_evap_file.setText(_translate("reservoirDialog", "Select File"))
        self.input_method_box_2.setTitle(_translate("reservoirDialog", "Input Method"))
        self.table_radio_3.setText(_translate("reservoirDialog", "Table"))
        self.input_radio_2.setText(_translate("reservoirDialog", "Input File"))
        self.res_tab_widget.setTabText(self.res_tab_widget.indexOf(self.evaporation_tab), _translate("reservoirDialog", "Evaportation"))
        self.level_vol_area_box.setTitle(_translate("reservoirDialog", "Level, Volume and Area File"))
        self.select_file.setText(_translate("reservoirDialog", "Select"))
        self.lev_vol_area_label.setText(_translate("reservoirDialog", "<html><head/><body><p align=\"center\"><span style=\" font-weight:400;\">Level (m), Volume (Mm</span><span style=\" font-weight:400; vertical-align:super;\">3</span><span style=\" font-weight:400;\">), Area (Km</span><span style=\" font-weight:400; vertical-align:super;\">2</span><span style=\" font-weight:400;\">)</span></p></body></html>"))
        self.storage_elev_det_box.setTitle(_translate("reservoirDialog", "Storage Elevation Details"))
        self.elev_area_coeff_label.setText(_translate("reservoirDialog", "Elevation Area Coeff."))
        self.vol_area_coeff.setText(_translate("reservoirDialog", "Volume Area Coeff. "))
        self.alpha_label.setText(_translate("reservoirDialog", "Alpha"))
        self.beta_label.setText(_translate("reservoirDialog", "Beta"))
        self.gamma_label.setText(_translate("reservoirDialog", "Gamma"))
        self.select_type_box.setTitle(_translate("reservoirDialog", "Select Type"))
        self.coeff_radio.setText(_translate("reservoirDialog", "Coefficient"))
        self.table_radio.setText(_translate("reservoirDialog", "Table"))
        self.res_tab_widget.setTabText(self.res_tab_widget.indexOf(self.storage_elev_tab), _translate("reservoirDialog", "Storage Elevation"))
        self.oper_info_box.setTitle(_translate("reservoirDialog", "Operational Information"))
        self.targ_stor_label.setText(_translate("reservoirDialog", "Target Storage"))
        self.tar_stor_unit.setText(_translate("reservoirDialog", "<html><head/><body><p>Mm<span style=\" vertical-align:super;\">3</span></p></body></html>"))
        self.stor_prob_label.setText(_translate("reservoirDialog", "Storage Probability"))
        self.rule_curve_box.setTitle(_translate("reservoirDialog", "Rule Curve (Mm3)"))
        self.curve_file_select.setText(_translate("reservoirDialog", "Select File"))
        item = self.rule_curve_table.verticalHeaderItem(0)
        item.setText(_translate("reservoirDialog", "Storage"))
        item = self.rule_curve_table.verticalHeaderItem(1)
        item.setText(_translate("reservoirDialog", "Add as constraint"))
        item = self.rule_curve_table.verticalHeaderItem(2)
        item.setText(_translate("reservoirDialog", "Flood Volume"))
        item = self.rule_curve_table.verticalHeaderItem(3)
        item.setText(_translate("reservoirDialog", "Add as constraint"))
        item = self.rule_curve_table.horizontalHeaderItem(0)
        item.setText(_translate("reservoirDialog", "1"))
        item = self.rule_curve_table.horizontalHeaderItem(1)
        item.setText(_translate("reservoirDialog", "2"))
        item = self.rule_curve_table.horizontalHeaderItem(2)
        item.setText(_translate("reservoirDialog", "3"))
        item = self.rule_curve_table.horizontalHeaderItem(3)
        item.setText(_translate("reservoirDialog", "4"))
        item = self.rule_curve_table.horizontalHeaderItem(4)
        item.setText(_translate("reservoirDialog", "5"))
        item = self.rule_curve_table.horizontalHeaderItem(5)
        item.setText(_translate("reservoirDialog", "6"))
        item = self.rule_curve_table.horizontalHeaderItem(6)
        item.setText(_translate("reservoirDialog", "7"))
        item = self.rule_curve_table.horizontalHeaderItem(7)
        item.setText(_translate("reservoirDialog", "8"))
        item = self.rule_curve_table.horizontalHeaderItem(8)
        item.setText(_translate("reservoirDialog", "9"))
        item = self.rule_curve_table.horizontalHeaderItem(9)
        item.setText(_translate("reservoirDialog", "10"))
        item = self.rule_curve_table.horizontalHeaderItem(10)
        item.setText(_translate("reservoirDialog", "11"))
        item = self.rule_curve_table.horizontalHeaderItem(11)
        item.setText(_translate("reservoirDialog", "12"))
        __sortingEnabled = self.rule_curve_table.isSortingEnabled()
        self.rule_curve_table.setSortingEnabled(False)
        item = self.rule_curve_table.item(1, 0)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(1, 1)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(1, 2)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(1, 3)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(1, 4)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(1, 5)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(1, 6)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(1, 7)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(1, 8)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(1, 9)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(1, 10)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(1, 11)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(3, 0)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(3, 1)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(3, 2)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(3, 3)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(3, 4)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(3, 5)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(3, 6)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(3, 7)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(3, 8)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(3, 9)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(3, 10)
        item.setText(_translate("reservoirDialog", "No"))
        item = self.rule_curve_table.item(3, 11)
        item.setText(_translate("reservoirDialog", "No"))
        self.rule_curve_table.setSortingEnabled(__sortingEnabled)
        self.target_rest_box.setTitle(_translate("reservoirDialog", "Target Restriction Levels Probability"))
        item = self.target_rest_table.horizontalHeaderItem(0)
        item.setText(_translate("reservoirDialog", "1"))
        item = self.target_rest_table.horizontalHeaderItem(1)
        item.setText(_translate("reservoirDialog", "2"))
        item = self.target_rest_table.horizontalHeaderItem(2)
        item.setText(_translate("reservoirDialog", "3"))
        self.input_method_box.setTitle(_translate("reservoirDialog", "Input Method"))
        self.table_radio_2.setText(_translate("reservoirDialog", "Table"))
        self.input_radio.setText(_translate("reservoirDialog", "Input File"))
        self.res_tab_widget.setTabText(self.res_tab_widget.indexOf(self.oper_info_tab), _translate("reservoirDialog", "Operational Information"))
        self.spillway_box.setTitle(_translate("reservoirDialog", "Spillways"))
        item = self.spillway_table.horizontalHeaderItem(0)
        item.setText(_translate("reservoirDialog", "Spillway Types"))
        item = self.spillway_table.horizontalHeaderItem(1)
        item.setText(_translate("reservoirDialog", "Crest Level (m)"))
        item = self.spillway_table.horizontalHeaderItem(2)
        item.setText(_translate("reservoirDialog", "Discharge Maximum (m3/sec)"))
        self.num_spill_label.setText(_translate("reservoirDialog", "Number of Spillways"))
        self.outlet_box.setTitle(_translate("reservoirDialog", "Outlets"))
        item = self.outlet_table.horizontalHeaderItem(0)
        item.setText(_translate("reservoirDialog", "Elevation (m)"))
        item = self.outlet_table.horizontalHeaderItem(1)
        item.setText(_translate("reservoirDialog", "Cross Section Area (m2)"))
        item = self.outlet_table.horizontalHeaderItem(2)
        item.setText(_translate("reservoirDialog", "Maximum Loss Coefficient"))
        item = self.outlet_table.horizontalHeaderItem(3)
        item.setText(_translate("reservoirDialog", "Minimum Loss Coefficient"))
        self.num_outlet_label.setText(_translate("reservoirDialog", "Number of Outlets"))
        self.res_tab_widget.setTabText(self.res_tab_widget.indexOf(self.spill_out_tab), _translate("reservoirDialog", "Spillway/Outlets"))

