# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\graps_graphics.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from ui.my_graphics_view import GraphicsView


class Ui_GRAPSInterface(object):
    def setupUi(self, GRAPSInterface):
        GRAPSInterface.setObjectName("GRAPSInterface")
        GRAPSInterface.setWindowModality(QtCore.Qt.NonModal)
        GRAPSInterface.resize(840, 836)
        GRAPSInterface.setMouseTracking(False)
        GRAPSInterface.setWindowOpacity(1.0)
        GRAPSInterface.setAutoFillBackground(False)
        GRAPSInterface.setDocumentMode(False)
        GRAPSInterface.setUnifiedTitleAndToolBarOnMac(True)
        self.centralWidget = QtWidgets.QWidget(GRAPSInterface)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.graphicsView = GraphicsView(self.centralWidget)
        self.graphicsView.viewport().setProperty(
            "cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.graphicsView.setVerticalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOn)
        self.graphicsView.setHorizontalScrollBarPolicy(
            QtCore.Qt.ScrollBarAlwaysOn)
        self.graphicsView.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.graphicsView.setRenderHints(
            QtGui.QPainter.SmoothPixmapTransform | QtGui.QPainter.TextAntialiasing)
        self.graphicsView.setTransformationAnchor(
            QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.graphicsView.setResizeAnchor(
            QtWidgets.QGraphicsView.AnchorUnderMouse)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_2.addWidget(self.graphicsView, 0, 0, 1, 1)
        GRAPSInterface.setCentralWidget(self.centralWidget)
        self.menubar = QtWidgets.QMenuBar(GRAPSInterface)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 840, 22))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menuGen_Setup = QtWidgets.QMenu(self.menubar)
        self.menuGen_Setup.setObjectName("menuGen_Setup")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        GRAPSInterface.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(GRAPSInterface)
        self.statusbar.setObjectName("statusbar")
        GRAPSInterface.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(GRAPSInterface)
        self.toolBar.setEnabled(True)
        self.toolBar.setMovable(True)
        self.toolBar.setObjectName("toolBar")
        GRAPSInterface.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew_File = QtWidgets.QAction(GRAPSInterface)
        self.actionNew_File.setObjectName("actionNew_File")
        self.actionOpen = QtWidgets.QAction(GRAPSInterface)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(GRAPSInterface)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(GRAPSInterface)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionPrint = QtWidgets.QAction(GRAPSInterface)
        self.actionPrint.setObjectName("actionPrint")
        self.actionPrint_Preview = QtWidgets.QAction(GRAPSInterface)
        self.actionPrint_Preview.setObjectName("actionPrint_Preview")
        self.actionClose = QtWidgets.QAction(GRAPSInterface)
        self.actionClose.setObjectName("actionClose")
        self.actionSave_and_Quit = QtWidgets.QAction(GRAPSInterface)
        self.actionSave_and_Quit.setObjectName("actionSave_and_Quit")
        self.actionWatershed = QtWidgets.QAction(GRAPSInterface)
        self.actionWatershed.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/W.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWatershed.setIcon(icon)
        self.actionWatershed.setIconVisibleInMenu(True)
        self.actionWatershed.setObjectName("actionWatershed")
        self.actionJunction = QtWidgets.QAction(GRAPSInterface)
        self.actionJunction.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/J.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionJunction.setIcon(icon1)
        self.actionJunction.setObjectName("actionJunction")
        self.actionReservoir = QtWidgets.QAction(GRAPSInterface)
        self.actionReservoir.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/R.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReservoir.setIcon(icon2)
        self.actionReservoir.setObjectName("actionReservoir")
        self.actionUser = QtWidgets.QAction(GRAPSInterface)
        self.actionUser.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/U.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUser.setIcon(icon3)
        self.actionUser.setObjectName("actionUser")
        self.actionN = QtWidgets.QAction(GRAPSInterface)
        self.actionN.setCheckable(True)
        self.actionN.setChecked(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/transparent.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionN.setIcon(icon4)
        self.actionN.setObjectName("actionN")
        self.actionInterBT = QtWidgets.QAction(GRAPSInterface)
        self.actionInterBT.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/I.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInterBT.setIcon(icon5)
        self.actionInterBT.setObjectName("actionInterBT")
        self.actionSink = QtWidgets.QAction(GRAPSInterface)
        self.actionSink.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/S.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSink.setIcon(icon6)
        self.actionSink.setObjectName("actionSink")
        self.actionLink = QtWidgets.QAction(GRAPSInterface)
        self.actionLink.setObjectName("actionLink")
        self.actionE = QtWidgets.QAction(GRAPSInterface)
        self.actionE.setObjectName("actionE")
        self.actionMV = QtWidgets.QAction(GRAPSInterface)
        self.actionMV.setCheckable(False)
        self.actionMV.setEnabled(False)
        self.actionMV.setVisible(False)
        self.actionMV.setIconVisibleInMenu(True)
        self.actionMV.setObjectName("actionMV")
        self.actionMS = QtWidgets.QAction(GRAPSInterface)
        self.actionMS.setVisible(False)
        self.actionMS.setObjectName("actionMS")
        self.actionG = QtWidgets.QAction(GRAPSInterface)
        self.actionG.setVisible(False)
        self.actionG.setObjectName("actionG")
        self.actionR = QtWidgets.QAction(GRAPSInterface)
        self.actionR.setVisible(False)
        self.actionR.setObjectName("actionR")
        self.actionOpen_2 = QtWidgets.QAction(GRAPSInterface)
        self.actionOpen_2.setObjectName("actionOpen_2")
        self.actionNew = QtWidgets.QAction(GRAPSInterface)
        self.actionNew.setObjectName("actionNew")
        self.actionSave_2 = QtWidgets.QAction(GRAPSInterface)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionGS = QtWidgets.QAction(GRAPSInterface)
        self.actionGS.setObjectName("actionGS")
        self.actionGeneral_Setup = QtWidgets.QAction(GRAPSInterface)
        self.actionGeneral_Setup.setObjectName("actionGeneral_Setup")
        self.menu_File.addAction(self.actionNew_File)
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionSave)
        self.menu_File.addAction(self.actionSave_As)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionClose)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionSave_and_Quit)
        self.menuGen_Setup.addAction(self.actionGeneral_Setup)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuGen_Setup.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen_2)
        self.toolBar.addAction(self.actionSave_2)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionGS)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionN)
        self.toolBar.addAction(self.actionReservoir)
        self.toolBar.addAction(self.actionUser)
        self.toolBar.addAction(self.actionJunction)
        self.toolBar.addAction(self.actionSink)
        self.toolBar.addAction(self.actionWatershed)
        self.toolBar.addAction(self.actionInterBT)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionLink)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionE)
        self.toolBar.addAction(self.actionMV)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionMS)
        self.toolBar.addAction(self.actionG)
        self.toolBar.addAction(self.actionR)

        self.retranslateUi(GRAPSInterface)
        QtCore.QMetaObject.connectSlotsByName(GRAPSInterface)

    def retranslateUi(self, GRAPSInterface):
        _translate = QtCore.QCoreApplication.translate
        GRAPSInterface.setWindowTitle(_translate(
            "GRAPSInterface", "GRAPS Interface"))
        self.menu_File.setTitle(_translate("GRAPSInterface", "File"))
        self.menuGen_Setup.setTitle(_translate("GRAPSInterface", "Gen. Setup"))
        self.menuHelp.setTitle(_translate("GRAPSInterface", "Help"))
        self.toolBar.setWindowTitle(_translate("GRAPSInterface", "toolBar"))
        self.actionNew_File.setText(_translate("GRAPSInterface", "New File"))
        self.actionNew_File.setStatusTip(
            _translate("GRAPSInterface", "New File"))
        self.actionOpen.setText(_translate("GRAPSInterface", "Open"))
        self.actionOpen.setStatusTip(_translate("GRAPSInterface", "Open"))
        self.actionSave.setText(_translate("GRAPSInterface", "Save"))
        self.actionSave.setStatusTip(_translate("GRAPSInterface", "Save"))
        self.actionSave_As.setText(_translate("GRAPSInterface", "Save As"))
        self.actionSave_As.setStatusTip(
            _translate("GRAPSInterface", "Save As"))
        self.actionPrint.setText(_translate("GRAPSInterface", "Print"))
        self.actionPrint.setStatusTip(_translate("GRAPSInterface", "Print"))
        self.actionPrint_Preview.setText(
            _translate("GRAPSInterface", "Print Preview"))
        self.actionPrint_Preview.setStatusTip(
            _translate("GRAPSInterface", "Print Preview"))
        self.actionClose.setText(_translate("GRAPSInterface", "Close"))
        self.actionClose.setStatusTip(_translate("GRAPSInterface", "Close"))
        self.actionSave_and_Quit.setText(
            _translate("GRAPSInterface", "Save and Quit"))
        self.actionSave_and_Quit.setStatusTip(
            _translate("GRAPSInterface", "Save and Quit"))
        self.actionWatershed.setText(_translate("GRAPSInterface", "Watershed"))
        self.actionWatershed.setToolTip(_translate(
            "GRAPSInterface", "Watershed (Ctrl+W)"))
        self.actionWatershed.setStatusTip(
            _translate("GRAPSInterface", "Watershed"))
        self.actionWatershed.setShortcut(
            _translate("GRAPSInterface", "Ctrl+W"))
        self.actionJunction.setText(_translate("GRAPSInterface", "Junction"))
        self.actionJunction.setToolTip(_translate(
            "GRAPSInterface", "Junction (Ctrl+J)"))
        self.actionJunction.setStatusTip(
            _translate("GRAPSInterface", "Junction"))
        self.actionJunction.setShortcut(_translate("GRAPSInterface", "Ctrl+J"))
        self.actionReservoir.setText(_translate("GRAPSInterface", "Reservoir"))
        self.actionReservoir.setToolTip(_translate(
            "GRAPSInterface", "Reservoir (Ctrl+R)"))
        self.actionReservoir.setStatusTip(
            _translate("GRAPSInterface", "Reservoir"))
        self.actionReservoir.setShortcut(
            _translate("GRAPSInterface", "Ctrl+R"))
        self.actionUser.setText(_translate("GRAPSInterface", "User"))
        self.actionUser.setToolTip(_translate(
            "GRAPSInterface", "User (Ctrl+U)"))
        self.actionUser.setStatusTip(_translate("GRAPSInterface", "User"))
        self.actionUser.setShortcut(_translate("GRAPSInterface", "Ctrl+U"))
        self.actionN.setText(_translate("GRAPSInterface", "None"))
        self.actionN.setToolTip(_translate(
            "GRAPSInterface", "N (Ctrl+Shift+N)"))
        self.actionN.setStatusTip(_translate("GRAPSInterface", "N"))
        self.actionN.setShortcut(_translate("GRAPSInterface", "Ctrl+Shift+N"))
        self.actionInterBT.setText(_translate(
            "GRAPSInterface", "Inter-Basin Transfer"))
        self.actionInterBT.setToolTip(_translate(
            "GRAPSInterface", "Inter-Basin Transfer (Ctrl+I)"))
        self.actionInterBT.setStatusTip(_translate(
            "GRAPSInterface", "Inter-Basin Transfer"))
        self.actionInterBT.setShortcut(_translate("GRAPSInterface", "Ctrl+I"))
        self.actionSink.setText(_translate("GRAPSInterface", "Sink"))
        self.actionSink.setToolTip(_translate(
            "GRAPSInterface", "Sink (Ctrl+Shift+S)"))
        self.actionSink.setStatusTip(_translate("GRAPSInterface", "Sink"))
        self.actionSink.setShortcut(
            _translate("GRAPSInterface", "Ctrl+Shift+S"))
        self.actionLink.setText(_translate("GRAPSInterface", "Link"))
        self.actionLink.setToolTip(_translate(
            "GRAPSInterface", "Link (Ctrl+L)"))
        self.actionLink.setStatusTip(_translate("GRAPSInterface", "Link"))
        self.actionLink.setShortcut(_translate("GRAPSInterface", "Ctrl+L"))
        self.actionE.setText(_translate("GRAPSInterface", "Export"))
        self.actionE.setToolTip(_translate("GRAPSInterface", "E (Ctrl+E)"))
        self.actionE.setStatusTip(_translate("GRAPSInterface", "E"))
        self.actionE.setShortcut(_translate("GRAPSInterface", "Ctrl+E"))
        self.actionMV.setText(_translate("GRAPSInterface", "MV"))
        self.actionMV.setToolTip(_translate("GRAPSInterface", "MV"))
        self.actionMV.setStatusTip(_translate("GRAPSInterface", "MV"))
        self.actionMS.setText(_translate("GRAPSInterface", "MS"))
        self.actionMS.setToolTip(_translate("GRAPSInterface", "MS"))
        self.actionMS.setStatusTip(_translate("GRAPSInterface", "MS"))
        self.actionG.setText(_translate("GRAPSInterface", "G"))
        self.actionG.setToolTip(_translate("GRAPSInterface", "G"))
        self.actionG.setStatusTip(_translate("GRAPSInterface", "G"))
        self.actionR.setText(_translate("GRAPSInterface", "R"))
        self.actionR.setToolTip(_translate("GRAPSInterface", "R"))
        self.actionR.setStatusTip(_translate("GRAPSInterface", "R"))
        self.actionOpen_2.setText(_translate("GRAPSInterface", "Open"))
        self.actionOpen_2.setToolTip(
            _translate("GRAPSInterface", "Open (Ctrl+O)"))
        self.actionOpen_2.setStatusTip(_translate("GRAPSInterface", "Open"))
        self.actionOpen_2.setShortcut(_translate("GRAPSInterface", "Ctrl+O"))
        self.actionNew.setText(_translate("GRAPSInterface", "New"))
        self.actionNew.setToolTip(_translate("GRAPSInterface", "New (Ctrl+N)"))
        self.actionNew.setStatusTip(_translate("GRAPSInterface", "New"))
        self.actionNew.setShortcut(_translate("GRAPSInterface", "Ctrl+N"))
        self.actionSave_2.setText(_translate("GRAPSInterface", "Save"))
        self.actionSave_2.setToolTip(
            _translate("GRAPSInterface", "Save (Ctrl+S)"))
        self.actionSave_2.setStatusTip(_translate("GRAPSInterface", "Save"))
        self.actionSave_2.setShortcut(_translate("GRAPSInterface", "Ctrl+S"))
        self.actionGS.setText(_translate("GRAPSInterface", "General Setup"))
        self.actionGS.setToolTip(_translate("GRAPSInterface", "General Setup"))
        self.actionGS.setStatusTip(_translate(
            "GRAPSInterface", "General Setup"))
        self.actionGeneral_Setup.setText(
            _translate("GRAPSInterface", "General Setup"))
        self.actionGeneral_Setup.setStatusTip(
            _translate("GRAPSInterface", "General Setup"))
