# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\link_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_link_dialog(object):
    def setupUi(self, link_dialog):
        link_dialog.setObjectName("link_dialog")
        link_dialog.resize(589, 486)
        self.gridLayout = QtWidgets.QGridLayout(link_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(link_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 1, 1, 1)
        self.link_name_display = QtWidgets.QLineEdit(link_dialog)
        self.link_name_display.setEnabled(False)
        self.link_name_display.setObjectName("link_name_display")
        self.gridLayout.addWidget(self.link_name_display, 1, 0, 1, 1)
        self.link_tabs_box = QtWidgets.QTabWidget(link_dialog)
        self.link_tabs_box.setObjectName("link_tabs_box")
        self.ident_tab = QtWidgets.QWidget()
        self.ident_tab.setObjectName("ident_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ident_tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.ident_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.link_id_display = QtWidgets.QLabel(self.groupBox)
        self.link_id_display.setObjectName("link_id_display")
        self.gridLayout_3.addWidget(self.link_id_display, 0, 2, 1, 1)
        self.link_name_edit = QtWidgets.QLabel(self.groupBox)
        self.link_name_edit.setObjectName("link_name_edit")
        self.gridLayout_3.addWidget(self.link_name_edit, 1, 0, 1, 1)
        self.link_name_edit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.link_name_edit_2.setObjectName("link_name_edit_2")
        self.gridLayout_3.addWidget(self.link_name_edit_2, 1, 2, 1, 1)
        self.link_id_label = QtWidgets.QLabel(self.groupBox)
        self.link_id_label.setObjectName("link_id_label")
        self.gridLayout_3.addWidget(self.link_id_label, 0, 0, 1, 1)
        self.type_start_label = QtWidgets.QLabel(self.groupBox)
        self.type_start_label.setObjectName("type_start_label")
        self.gridLayout_3.addWidget(self.type_start_label, 3, 0, 1, 1)
        self.end_node_label = QtWidgets.QLabel(self.groupBox)
        self.end_node_label.setObjectName("end_node_label")
        self.gridLayout_3.addWidget(self.end_node_label, 4, 0, 1, 1)
        self.type_end_display = QtWidgets.QLabel(self.groupBox)
        self.type_end_display.setObjectName("type_end_display")
        self.gridLayout_3.addWidget(self.type_end_display, 5, 2, 1, 1)
        self.start_node_label = QtWidgets.QLabel(self.groupBox)
        self.start_node_label.setObjectName("start_node_label")
        self.gridLayout_3.addWidget(self.start_node_label, 2, 0, 1, 1)
        self.end_node_display = QtWidgets.QLabel(self.groupBox)
        self.end_node_display.setObjectName("end_node_display")
        self.gridLayout_3.addWidget(self.end_node_display, 4, 2, 1, 1)
        self.type_end_label = QtWidgets.QLabel(self.groupBox)
        self.type_end_label.setObjectName("type_end_label")
        self.gridLayout_3.addWidget(self.type_end_label, 5, 0, 1, 1)
        self.start_node_display = QtWidgets.QLabel(self.groupBox)
        self.start_node_display.setObjectName("start_node_display")
        self.gridLayout_3.addWidget(self.start_node_display, 2, 2, 1, 1)
        self.type_start_display = QtWidgets.QLabel(self.groupBox)
        self.type_start_display.setObjectName("type_start_display")
        self.gridLayout_3.addWidget(self.type_start_display, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.link_tabs_box.addTab(self.ident_tab, "")
        self.discharge_tab = QtWidgets.QWidget()
        self.discharge_tab.setObjectName("discharge_tab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.discharge_tab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.discharge_box = QtWidgets.QGroupBox(self.discharge_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.discharge_box.sizePolicy().hasHeightForWidth())
        self.discharge_box.setSizePolicy(sizePolicy)
        self.discharge_box.setObjectName("discharge_box")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.discharge_box)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.min_disch_label = QtWidgets.QLabel(self.discharge_box)
        self.min_disch_label.setObjectName("min_disch_label")
        self.gridLayout_5.addWidget(self.min_disch_label, 0, 0, 1, 1)
        self.min_disch_edit = QtWidgets.QLineEdit(self.discharge_box)
        self.min_disch_edit.setObjectName("min_disch_edit")
        self.gridLayout_5.addWidget(self.min_disch_edit, 0, 1, 1, 1)
        self.min_disch_units = QtWidgets.QLabel(self.discharge_box)
        self.min_disch_units.setObjectName("min_disch_units")
        self.gridLayout_5.addWidget(self.min_disch_units, 0, 2, 1, 1)
        self.max_disch_label = QtWidgets.QLabel(self.discharge_box)
        self.max_disch_label.setObjectName("max_disch_label")
        self.gridLayout_5.addWidget(self.max_disch_label, 1, 0, 1, 1)
        self.max_disch_edit = QtWidgets.QLineEdit(self.discharge_box)
        self.max_disch_edit.setObjectName("max_disch_edit")
        self.gridLayout_5.addWidget(self.max_disch_edit, 1, 1, 1, 1)
        self.loss_fact_label = QtWidgets.QLabel(self.discharge_box)
        self.loss_fact_label.setObjectName("loss_fact_label")
        self.gridLayout_5.addWidget(self.loss_fact_label, 2, 0, 1, 1)
        self.loss_fact_edit = QtWidgets.QLineEdit(self.discharge_box)
        self.loss_fact_edit.setObjectName("loss_fact_edit")
        self.gridLayout_5.addWidget(self.loss_fact_edit, 2, 1, 1, 1)
        self.return_flow_Ques_box = QtWidgets.QGroupBox(self.discharge_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.return_flow_Ques_box.sizePolicy().hasHeightForWidth())
        self.return_flow_Ques_box.setSizePolicy(sizePolicy)
        self.return_flow_Ques_box.setObjectName("return_flow_Ques_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.return_flow_Ques_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.yes_rad_button = QtWidgets.QRadioButton(self.return_flow_Ques_box)
        self.yes_rad_button.setObjectName("yes_rad_button")
        self.verticalLayout.addWidget(self.yes_rad_button)
        self.no_rad_button = QtWidgets.QRadioButton(self.return_flow_Ques_box)
        self.no_rad_button.setObjectName("no_rad_button")
        self.verticalLayout.addWidget(self.no_rad_button)
        self.gridLayout_5.addWidget(self.return_flow_Ques_box, 3, 0, 1, 2)
        self.max_disch_units = QtWidgets.QLabel(self.discharge_box)
        self.max_disch_units.setObjectName("max_disch_units")
        self.gridLayout_5.addWidget(self.max_disch_units, 1, 2, 1, 1)
        self.gridLayout_4.addWidget(self.discharge_box, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 1, 1, 1)
        self.return_flow_box = QtWidgets.QGroupBox(self.discharge_tab)
        self.return_flow_box.setObjectName("return_flow_box")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.return_flow_box)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.return_flow_table = QtWidgets.QTableWidget(self.return_flow_box)
        self.return_flow_table.setObjectName("return_flow_table")
        self.return_flow_table.setColumnCount(1)
        self.return_flow_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.return_flow_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.return_flow_table.setHorizontalHeaderItem(0, item)
        self.gridLayout_6.addWidget(self.return_flow_table, 1, 0, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 0, 2, 1, 1)
        self.nlags_label = QtWidgets.QLabel(self.return_flow_box)
        self.nlags_label.setObjectName("nlags_label")
        self.gridLayout_6.addWidget(self.nlags_label, 0, 0, 1, 1)
        self.nlags_edit = QtWidgets.QLineEdit(self.return_flow_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nlags_edit.sizePolicy().hasHeightForWidth())
        self.nlags_edit.setSizePolicy(sizePolicy)
        self.nlags_edit.setObjectName("nlags_edit")
        self.gridLayout_6.addWidget(self.nlags_edit, 0, 1, 1, 1)
        self.gridLayout_4.addWidget(self.return_flow_box, 1, 0, 1, 2)
        self.link_tabs_box.addTab(self.discharge_tab, "")
        self.gridLayout.addWidget(self.link_tabs_box, 0, 0, 1, 2, QtCore.Qt.AlignTop)
        self.link_name_edit.setBuddy(self.link_name_edit_2)
        self.min_disch_label.setBuddy(self.min_disch_edit)
        self.max_disch_label.setBuddy(self.max_disch_edit)
        self.loss_fact_label.setBuddy(self.loss_fact_edit)
        self.nlags_label.setBuddy(self.nlags_edit)

        self.retranslateUi(link_dialog)
        self.link_tabs_box.setCurrentIndex(0)
        self.buttonBox.accepted.connect(link_dialog.accept)
        self.buttonBox.rejected.connect(link_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(link_dialog)
        link_dialog.setTabOrder(self.link_tabs_box, self.link_name_edit_2)
        link_dialog.setTabOrder(self.link_name_edit_2, self.link_name_display)
        link_dialog.setTabOrder(self.link_name_display, self.buttonBox)
        link_dialog.setTabOrder(self.buttonBox, self.min_disch_edit)
        link_dialog.setTabOrder(self.min_disch_edit, self.max_disch_edit)
        link_dialog.setTabOrder(self.max_disch_edit, self.loss_fact_edit)
        link_dialog.setTabOrder(self.loss_fact_edit, self.yes_rad_button)
        link_dialog.setTabOrder(self.yes_rad_button, self.no_rad_button)
        link_dialog.setTabOrder(self.no_rad_button, self.nlags_edit)
        link_dialog.setTabOrder(self.nlags_edit, self.return_flow_table)

    def retranslateUi(self, link_dialog):
        _translate = QtCore.QCoreApplication.translate
        link_dialog.setWindowTitle(_translate("link_dialog", "Link"))
        self.groupBox.setTitle(_translate("link_dialog", "Identification"))
        self.link_id_display.setText(_translate("link_dialog", "2"))
        self.link_name_edit.setText(_translate("link_dialog", "Link Name"))
        self.link_id_label.setText(_translate("link_dialog", "Link ID"))
        self.type_start_label.setText(_translate("link_dialog", "Type Start Node"))
        self.end_node_label.setText(_translate("link_dialog", "End Node"))
        self.type_end_display.setText(_translate("link_dialog", "U"))
        self.start_node_label.setText(_translate("link_dialog", "Start Node"))
        self.end_node_display.setText(_translate("link_dialog", "1"))
        self.type_end_label.setText(_translate("link_dialog", "Type End Node"))
        self.start_node_display.setText(_translate("link_dialog", "1"))
        self.type_start_display.setText(_translate("link_dialog", "R"))
        self.link_tabs_box.setTabText(self.link_tabs_box.indexOf(self.ident_tab), _translate("link_dialog", "Identification"))
        self.discharge_box.setTitle(_translate("link_dialog", "Discharge"))
        self.min_disch_label.setText(_translate("link_dialog", "Minimum Discharge"))
        self.min_disch_units.setText(_translate("link_dialog", "<html><head/><body><p>m<span style=\" vertical-align:super;\">3</span>/sec</p></body></html>"))
        self.max_disch_label.setText(_translate("link_dialog", "Maximum Discharge"))
        self.loss_fact_label.setText(_translate("link_dialog", "Loss Factor"))
        self.return_flow_Ques_box.setTitle(_translate("link_dialog", "If it is return flow?"))
        self.yes_rad_button.setText(_translate("link_dialog", "Yes"))
        self.no_rad_button.setText(_translate("link_dialog", "No"))
        self.max_disch_units.setText(_translate("link_dialog", "<html><head/><body><p>m<span style=\" vertical-align:super;\">3</span>/sec</p></body></html>"))
        self.return_flow_box.setTitle(_translate("link_dialog", "Return Flows"))
        item = self.return_flow_table.verticalHeaderItem(0)
        item.setText(_translate("link_dialog", "A"))
        item = self.return_flow_table.horizontalHeaderItem(0)
        item.setText(_translate("link_dialog", "1"))
        self.nlags_label.setText(_translate("link_dialog", "Nlags"))
        self.link_tabs_box.setTabText(self.link_tabs_box.indexOf(self.discharge_tab), _translate("link_dialog", "Discharge"))
